#!/usr/bin/env bash
# run.sh — add-on entrypoint.
# Reads HA add-on options from /data/options.json, writes heyu x10config, starts
# the heyu engine, then runs the MQTT bridge in the foreground.
set -euo pipefail

OPTIONS_FILE="/data/options.json"

# Read options via jq (HA injects /data/options.json for add-ons).
if [ -f "$OPTIONS_FILE" ]; then
  CM11_TTY=$(jq -r .cm11_tty "$OPTIONS_FILE")
  W800_TTY=$(jq -r .w800_tty "$OPTIONS_FILE")
  W800_TYPE=$(jq -r .w800_type "$OPTIONS_FILE")
  HOUSECODE=$(jq -r .housecode "$OPTIONS_FILE")
  TOPIC_PREFIX=$(jq -r .topic_prefix "$OPTIONS_FILE")
  DISCOVERY_PREFIX=$(jq -r .discovery_prefix "$OPTIONS_FILE")
  MQTT_HOST=$(jq -r .mqtt_host "$OPTIONS_FILE")
  MQTT_PORT=$(jq -r .mqtt_port "$OPTIONS_FILE")
  MQTT_USER=$(jq -r .mqtt_user "$OPTIONS_FILE")
  MQTT_PASSWORD=$(jq -r .mqtt_password "$OPTIONS_FILE")
  LOG_LEVEL=$(jq -r .log_level "$OPTIONS_FILE")
else
  # Fallback to env for local testing outside HA OS.
  CM11_TTY="${CM11_TTY:-/dev/ttyUSB1}"
  W800_TTY="${W800_TTY:-/dev/ttyUSB0}"
  W800_TYPE="${W800_TYPE:-W800RF32A}"
  HOUSECODE="${HOUSECODE:-A}"
  TOPIC_PREFIX="${TOPIC_PREFIX:-x10}"
  DISCOVERY_PREFIX="${DISCOVERY_PREFIX:-homeassistant}"
  MQTT_HOST="${MQTT_HOST:-core-mosquitto}"
  MQTT_PORT="${MQTT_PORT:-1883}"
  MQTT_USER="${MQTT_USER:-}"
  MQTT_PASSWORD="${MQTT_PASSWORD:-}"
  LOG_LEVEL="${LOG_LEVEL:-INFO}"
fi

export LOG_LEVEL

# heyu looks for ~/.heyu/x10config
mkdir -p /root/.heyu
cat > /root/.heyu/x10config <<EOF
# Generated by heyu-x10-bridge add-on
TTY ${CM11_TTY}
TTY_AUX ${W800_TTY} ${W800_TYPE}
HOUSECODE ${HOUSECODE}
START_ENGINE AUTO
EOF

echo "[run.sh] x10config written:"
cat /root/.heyu/x10config

# Start the heyu engine (handles CM11 + W800; maintains state; runs aux for RF).
# `heyu start` brings up engine + relay per START_ENGINE AUTO.
heyu start || heyu engine &
sleep 2

# Run the MQTT bridge in the foreground (it runs `heyu monitor` internally).
exec python3 /app/bridge.py \
  --devices /app/devices.yaml \
  --heyu heyu \
  --mqtt-host "${MQTT_HOST}" \
  --mqtt-port "${MQTT_PORT}" \
  --mqtt-user "${MQTT_USER}" \
  --mqtt-password "${MQTT_PASSWORD}" \
  --topic-prefix "${TOPIC_PREFIX}" \
  --discovery-prefix "${DISCOVERY_PREFIX}"
